### ISSUE TITLE
Incompatable Build Tools

### ISSUE THREAD

**Issue by nvarner** [MycroftAI/Mycroft-Android#84]
Android studio is warning me that the build tools version is incompatible with the Android Gradle plugin. The app still compiles, but uses a newer version of build tools.

```WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: mobile, shared, wear```

I don't know enough about Android to be certain that this isn't my fault, and I don't know what the best solution is, so I don't want to submit a PR right now. Does anyone else have this problem?

**Comment by skraynick** [comment]
I will take a peak later today. Thanks.

**Comment by skraynick** [comment]
@nvarner this should be fixed now... if so please close.

**Comment by nvarner** [comment]
I still have this issue, but I'm sure now that this isn't just a problem on my computer. The project build.gradle includes [the Android Gradle plugin 3.2.1 as a dependency](https://github.com/MycroftAI/Mycroft-Android/blob/master/build.gradle#L11) and [27.0.3 as the build tools version](https://github.com/MycroftAI/Mycroft-Android/blob/master/build.gradle#L66). Based on the [official Android Gradle plugin release notes](https://developer.android.com/studio/releases/gradle-plugin#3-2-0), this version only supports build tools 28.0.3 and above.

**Comment by nvarner** [comment]
I've created pull request #86 which solves my problem by updating the Build Tools Version to 28.0.3.

**Comment by Doomsdayrs** [comment]
This is likely stale now

**Comment by nvarner** [comment]
Seems like you're right. However, I wasn't able to compile the new version to confirm. I get the error `File google-sevices.json is missing. The Google Services Plugin cannot function without it.`. If I can't fix that soon or don't have the time to try, I'll close this under the assumption that it's no longer an issue.
